# AUTOGENERATED by tf-ansible-gen from firezone_oidc/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: 3eb2c8935a5210344d30aaa7653380a7664ac95d2facc0866c238f6008957884

variable "arguments" {
  description = "Typed payload from argument_specs.yml. All fields optional with defaults."
  type = object({
    firezone_oidc_dir = optional(string, "/opt/garuda/firezone")
    firezone_oidc_server_url = optional(string)
    firezone_oidc_providers = optional(map(any))
    firezone_oidc_api_url = optional(string)
  })
  default = {}
}

variable "host_name" {
  description = "Inventory host that should receive this workload apply or cleanup."
  type        = string
}

variable "connection_data" {
  description = "Normalized transport/auth contract for the target Linux host."
  type = object({
    host                 = string
    user                 = string
    password             = optional(string)
    connection           = string
    network_os           = string
    ssh_private_key_file = optional(string)
    ssh_private_key      = optional(string)
    instance_token       = string
  })
  sensitive = true
}

variable "extra_hostvars" {
  description = "Optional additional hostvars merged into ansible_host variables."
  type        = map(any)
  default     = {}
}

