# AUTOGENERATED by tf-ansible-gen from firezone_oidc/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: 3eb2c8935a5210344d30aaa7653380a7664ac95d2facc0866c238f6008957884
terraform {
  required_version = ">= 1.6"
}
