# AUTOGENERATED by tf-ansible-gen from linux_host_prerequisites/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: f00cbaca0e532932b1e72b7951e7a795da6feefbb0d949857f82bed3ada0ea14
output "applied" {
  description = "ID of the apply resource. Use for downstream depends_on."
  value       = terraform_data.apply.id
}
