# AUTOGENERATED by tf-ansible-gen from linux_host_prerequisites/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: f00cbaca0e532932b1e72b7951e7a795da6feefbb0d949857f82bed3ada0ea14

variable "arguments" {
  description = "Typed payload from argument_specs.yml. All fields optional with defaults."
  type = object({
    docker_daemon_config = optional(any, {})
    reboot_on_change = optional(bool, true)
  })
  default = {}
}

variable "host_name" {
  description = "Inventory host that should receive this workload apply or cleanup."
  type        = string
}

variable "connection_data" {
  description = "Normalized transport/auth contract for the target Linux host."
  type = object({
    host                 = string
    user                 = string
    password             = optional(string)
    connection           = string
    network_os           = string
    ssh_private_key_file = optional(string)
    ssh_private_key      = optional(string)
    instance_token       = string
  })
  sensitive = true
}

variable "extra_hostvars" {
  description = "Optional additional hostvars merged into ansible_host variables."
  type        = map(any)
  default     = {}
}

