# AUTOGENERATED by tf-ansible-gen from wireguard/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: 55d29349c895cc301d94b146fe0d4b72c6e94c03d8e9d023631ffad961552083
locals {
  contract_version = "sha256:55d29349c895cc301d94b146fe0d4b72c6e94c03d8e9d023631ffad961552083"
  payload = {
    wireguard_tunnel_name = var.arguments.wireguard_tunnel_name
    wireguard_interface_name = var.arguments.wireguard_interface_name
    wireguard_address = var.arguments.wireguard_address
    wireguard_private_key = var.arguments.wireguard_private_key
    wireguard_table = var.arguments.wireguard_table
    wireguard_listen_port = var.arguments.wireguard_listen_port
    wireguard_public_endpoint = var.arguments.wireguard_public_endpoint
    wireguard_peer_public_key = var.arguments.wireguard_peer_public_key
    wireguard_peer_address = var.arguments.wireguard_peer_address
    wireguard_peer_endpoint_host = var.arguments.wireguard_peer_endpoint_host
    wireguard_peer_listen_port = var.arguments.wireguard_peer_listen_port
    wireguard_peer_preshared_key = var.arguments.wireguard_peer_preshared_key
    wireguard_peer_persistent_keepalive = var.arguments.wireguard_peer_persistent_keepalive
    wireguard_allowed_nets = var.arguments.wireguard_allowed_nets
    wireguard_post_up = var.arguments.wireguard_post_up
    wireguard_pre_down = var.arguments.wireguard_pre_down
    wireguard_labels = var.arguments.wireguard_labels
    wireguard_nic_attach = var.arguments.wireguard_nic_attach
    wireguard_mesh_root = var.arguments.wireguard_mesh_root
    wireguard_image = var.arguments.wireguard_image
    wireguard_ops_root = var.arguments.wireguard_ops_root
  }
  payload_json = jsonencode(local.payload)

  ssh_key_path        = try(var.connection_data.ssh_private_key_file, null)
  ssh_key_raw         = try(var.connection_data.ssh_private_key, null)
  ssh_key_file_effect = local.ssh_key_path != null ? pathexpand(local.ssh_key_path) : ""

  role_dir        = abspath("${path.module}/..")
  helper_script   = abspath("${path.module}/files/run_apply.sh")
  collection_root = abspath("${path.module}/../../..")
}

resource "terraform_data" "apply" {
  triggers_replace = {
    contract_version = local.contract_version
    payload_hash     = sha256(local.payload_json)
    instance_token   = var.connection_data.instance_token
  }

  input = {
    contract_version    = local.contract_version
    role_dir            = local.role_dir
    helper_script       = local.helper_script
    collection_root     = local.collection_root
    workload_kind       = "wireguard"
    workload_payload    = local.payload_json
    host_name           = var.host_name
    inventory_host      = var.connection_data.host
    ansible_user        = var.connection_data.user
    ansible_connection  = var.connection_data.connection
    ansible_network_os  = var.connection_data.network_os
    ssh_key_file_effect = local.ssh_key_file_effect
    ssh_key_raw         = local.ssh_key_raw
    ansible_password    = try(var.connection_data.password, null)
    extra_hostvars_json = jsonencode(var.extra_hostvars)
  }

  provisioner "local-exec" {
    command = self.input.helper_script
    environment = {
      contract_version                = self.input.contract_version
      role_dir                        = self.input.role_dir
      workload_kind                   = self.input.workload_kind
      workload_lifecycle              = "provision"
      workload_payload                = self.input.workload_payload
      collection_root                 = self.input.collection_root
      host_name                       = self.input.host_name
      inventory_host                  = self.input.inventory_host
      ansible_user                    = self.input.ansible_user
      ansible_connection              = self.input.ansible_connection
      ansible_network_os              = self.input.ansible_network_os
      ansible_ssh_private_key_file    = self.input.ssh_key_file_effect
      ansible_ssh_private_key_content = self.input.ssh_key_raw != null ? self.input.ssh_key_raw : ""
      ansible_password                = self.input.ansible_password != null ? self.input.ansible_password : ""
      extra_hostvars                  = self.input.extra_hostvars_json
    }
  }

  provisioner "local-exec" {
    when    = destroy
    command = "test -f \"${self.input.helper_script}\" && \"${self.input.helper_script}\" || echo \"WARN: helper_script not found, skipping destroy\""
    environment = {
      contract_version                = self.input.contract_version
      role_dir                        = self.input.role_dir
      workload_kind                   = self.input.workload_kind
      workload_lifecycle              = "destroy"
      workload_payload                = self.input.workload_payload
      collection_root                 = self.input.collection_root
      host_name                       = self.input.host_name
      inventory_host                  = self.input.inventory_host
      ansible_user                    = self.input.ansible_user
      ansible_connection              = self.input.ansible_connection
      ansible_network_os              = self.input.ansible_network_os
      ansible_ssh_private_key_file    = self.input.ssh_key_file_effect
      ansible_ssh_private_key_content = self.input.ssh_key_raw != null ? self.input.ssh_key_raw : ""
      ansible_password                = self.input.ansible_password != null ? self.input.ansible_password : ""
      extra_hostvars                  = self.input.extra_hostvars_json
    }
  }
}
