# AUTOGENERATED by tf-ansible-gen from wireguard/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: 55d29349c895cc301d94b146fe0d4b72c6e94c03d8e9d023631ffad961552083

variable "arguments" {
  description = <<-EOT
    Typed payload mirroring provision.options in argument_specs.yml.

    Fields declared `required: true` (no `default:`) in argument_specs are
    required at the Terraform layer too — `tofu plan` fails fast if the
    caller omits them. Fields with a `default:` are rendered as
    `optional(<type>, <default>)`. All other fields are
    `optional(<type>)` and arrive as null when omitted (the role must
    handle null explicitly).
  EOT
  type = object({
    wireguard_tunnel_name = optional(string)
    wireguard_interface_name = string
    wireguard_address = string
    wireguard_private_key = string
    wireguard_table = any
    wireguard_listen_port = optional(number)
    wireguard_public_endpoint = optional(string)
    wireguard_peer_public_key = string
    wireguard_peer_address = string
    wireguard_peer_endpoint_host = optional(string)
    wireguard_peer_listen_port = optional(number)
    wireguard_peer_preshared_key = optional(string)
    wireguard_peer_persistent_keepalive = optional(number)
    wireguard_allowed_nets = optional(list(string), [])
    wireguard_post_up = optional(string)
    wireguard_pre_down = optional(string)
    wireguard_labels = optional(map(any), {})
    wireguard_nic_attach = optional(list(string), [])
    wireguard_mesh_root = optional(string, "/opt/garuda/wg_tunnels")
    wireguard_image = string
    wireguard_ops_root = optional(string, "/opt/garuda/ops")
  })
}

variable "host_name" {
  description = "Inventory host that should receive this workload apply or cleanup."
  type        = string
}

variable "connection_data" {
  description = "Normalized transport/auth contract for the target Linux host."
  type = object({
    host                 = string
    user                 = string
    password             = optional(string)
    connection           = string
    network_os           = string
    ssh_private_key_file = optional(string)
    ssh_private_key      = optional(string)
    instance_token       = string
  })
  sensitive = true
}

variable "extra_hostvars" {
  description = "Optional additional hostvars merged into ansible_host variables."
  type        = map(any)
  default     = {}
}

