# AUTOGENERATED by tf-ansible-gen from wireguard/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: 55d29349c895cc301d94b146fe0d4b72c6e94c03d8e9d023631ffad961552083
terraform {
  required_version = ">= 1.6"
}
