# AUTOGENERATED by tf-ansible-gen from firezone/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: b196e12f639fccc3a665713d8948f3221e78536cf49dcc96e980ffc006d3949e

variable "arguments" {
  description = <<-EOT
    Typed payload mirroring provision.options in argument_specs.yml.

    Fields declared `required: true` (no `default:`) in argument_specs are
    required at the Terraform layer too — `tofu plan` fails fast if the
    caller omits them. Fields with a `default:` are rendered as
    `optional(<type>, <default>)`. All other fields are
    `optional(<type>)` and arrive as null when omitted (the role must
    handle null explicitly).
  EOT
  type = object({
    fz_firezone_dir = string
    fz_firezone_image = string
    firezone_main_compose_file = string
    fz_admin_password = optional(string)
    fz_admin = optional(string, "fz-admin@localhost")
    fz_client_subnet = optional(string, "10.11.0.0/24")
    fz_wireguard_port = optional(string, "51620")
    fz_firezone_https = optional(bool, true)
    fz_server_url = optional(string)
    fz_mgmt_subnet = optional(string)
    fz_nic_attach = optional(list(string), ["backbone"])
    fz_masquerade = optional(bool, false)
    firezone_labels = optional(map(any), {})
  })
}

variable "host_name" {
  description = "Inventory host that should receive this workload apply or cleanup."
  type        = string
}

variable "connection_data" {
  description = "Normalized transport/auth contract for the target Linux host."
  type = object({
    host                 = string
    user                 = string
    password             = optional(string)
    connection           = string
    network_os           = string
    ssh_private_key_file = optional(string)
    ssh_private_key      = optional(string)
    instance_token       = string
  })
  sensitive = true
}

variable "extra_hostvars" {
  description = "Optional additional hostvars merged into ansible_host variables."
  type        = map(any)
  default     = {}
}

