# AUTOGENERATED by tf-ansible-gen from firezone/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: b196e12f639fccc3a665713d8948f3221e78536cf49dcc96e980ffc006d3949e
terraform {
  required_version = ">= 1.6"
}
