# AUTOGENERATED by tf-ansible-gen from ipt_server/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: d47bd8e85bd63cdee38301381e52ce5d840421856e5b09dc3447757e1f732aad
output "applied" {
  description = "ID of the apply resource. Use for downstream depends_on."
  value       = terraform_data.apply.id
}
