# AUTOGENERATED by tf-ansible-gen from ipt_server/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: d47bd8e85bd63cdee38301381e52ce5d840421856e5b09dc3447757e1f732aad

variable "arguments" {
  description = "Typed payload from argument_specs.yml. All fields optional with defaults."
  type = object({
    ipt_server_dir = optional(string)
    ipt_server_image = optional(string)
    ipt_powerdns_image = optional(string)
    ipt_interfaces = optional(list(string), [])
    ipt_routes = optional(list(object({ route = list(object({ gw = optional(string), dev = optional(string) })), rules = list(string) })), [])
    ipt_nic_attach = optional(list(string), [])
    ipt_clean_conntrack = optional(bool, false)
    ipt_domain_route_ttl = optional(number, 300)
    ipt_server_labels = optional(map(any), {})
    ipt_pinning_egress = optional(map(any), {})
    ipt_pinning_ttl = optional(number, 86400)
  })
  default = {}
}

variable "host_name" {
  description = "Inventory host that should receive this workload apply or cleanup."
  type        = string
}

variable "connection_data" {
  description = "Normalized transport/auth contract for the target Linux host."
  type = object({
    host                 = string
    user                 = string
    password             = optional(string)
    connection           = string
    network_os           = string
    ssh_private_key_file = optional(string)
    ssh_private_key      = optional(string)
    instance_token       = string
  })
  sensitive = true
}

variable "extra_hostvars" {
  description = "Optional additional hostvars merged into ansible_host variables."
  type        = map(any)
  default     = {}
}

