# AUTOGENERATED by tf-ansible-gen from backbone_network/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: c94467188cd8564d03936a6ac5e30e55260d471602102b456edc843fd2447700
locals {
  contract_version = "sha256:c94467188cd8564d03936a6ac5e30e55260d471602102b456edc843fd2447700"
  payload = {
    backbone_dir = var.arguments.backbone_dir
    backbone_subnet = var.arguments.backbone_subnet
    border_subnet = var.arguments.border_subnet
  }
  payload_json = jsonencode(local.payload)

  ssh_key_path        = try(var.connection_data.ssh_private_key_file, null)
  ssh_key_raw         = try(var.connection_data.ssh_private_key, null)
  ssh_key_file_effect = local.ssh_key_path != null ? pathexpand(local.ssh_key_path) : ""

  role_dir        = abspath("${path.module}/..")
  helper_script   = abspath("${path.module}/files/run_apply.sh")
  collection_root = abspath("${path.module}/../../..")
}

resource "terraform_data" "apply" {
  triggers_replace = {
    contract_version = local.contract_version
    payload_hash     = sha256(local.payload_json)
    instance_token   = var.connection_data.instance_token
  }

  input = {
    contract_version    = local.contract_version
    role_dir            = local.role_dir
    helper_script       = local.helper_script
    collection_root     = local.collection_root
    workload_kind       = "backbone_network"
    workload_payload    = local.payload_json
    host_name           = var.host_name
    inventory_host      = var.connection_data.host
    ansible_user        = var.connection_data.user
    ansible_connection  = var.connection_data.connection
    ansible_network_os  = var.connection_data.network_os
    ssh_key_file_effect = local.ssh_key_file_effect
    ssh_key_raw         = local.ssh_key_raw
    ansible_password    = try(var.connection_data.password, null)
    extra_hostvars_json = jsonencode(var.extra_hostvars)
  }

  provisioner "local-exec" {
    command = self.input.helper_script
    environment = {
      contract_version                = self.input.contract_version
      role_dir                        = self.input.role_dir
      workload_kind                   = self.input.workload_kind
      workload_lifecycle              = "provision"
      workload_payload                = self.input.workload_payload
      collection_root                 = self.input.collection_root
      host_name                       = self.input.host_name
      inventory_host                  = self.input.inventory_host
      ansible_user                    = self.input.ansible_user
      ansible_connection              = self.input.ansible_connection
      ansible_network_os              = self.input.ansible_network_os
      ansible_ssh_private_key_file    = self.input.ssh_key_file_effect
      ansible_ssh_private_key_content = self.input.ssh_key_raw != null ? self.input.ssh_key_raw : ""
      ansible_password                = self.input.ansible_password != null ? self.input.ansible_password : ""
      extra_hostvars                  = self.input.extra_hostvars_json
    }
  }

  provisioner "local-exec" {
    when    = destroy
    command = "test -f \"${self.input.helper_script}\" && \"${self.input.helper_script}\" || echo \"WARN: helper_script not found, skipping destroy\""
    environment = {
      contract_version                = self.input.contract_version
      role_dir                        = self.input.role_dir
      workload_kind                   = self.input.workload_kind
      workload_lifecycle              = "destroy"
      workload_payload                = self.input.workload_payload
      collection_root                 = self.input.collection_root
      host_name                       = self.input.host_name
      inventory_host                  = self.input.inventory_host
      ansible_user                    = self.input.ansible_user
      ansible_connection              = self.input.ansible_connection
      ansible_network_os              = self.input.ansible_network_os
      ansible_ssh_private_key_file    = self.input.ssh_key_file_effect
      ansible_ssh_private_key_content = self.input.ssh_key_raw != null ? self.input.ssh_key_raw : ""
      ansible_password                = self.input.ansible_password != null ? self.input.ansible_password : ""
      extra_hostvars                  = self.input.extra_hostvars_json
    }
  }
}
