# AUTOGENERATED by tf-ansible-gen from backbone_network/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: c94467188cd8564d03936a6ac5e30e55260d471602102b456edc843fd2447700
output "applied" {
  description = "ID of the apply resource. Use for downstream depends_on."
  value       = terraform_data.apply.id
}
