# AUTOGENERATED by tf-ansible-gen from backbone_network/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: c94467188cd8564d03936a6ac5e30e55260d471602102b456edc843fd2447700

variable "arguments" {
  description = "Typed payload from argument_specs.yml. All fields optional with defaults."
  type = object({
    backbone_dir = optional(string)
    backbone_subnet = optional(string)
    border_subnet = optional(string)
  })
  default = {}
}

variable "host_name" {
  description = "Inventory host that should receive this workload apply or cleanup."
  type        = string
}

variable "connection_data" {
  description = "Normalized transport/auth contract for the target Linux host."
  type = object({
    host                 = string
    user                 = string
    password             = optional(string)
    connection           = string
    network_os           = string
    ssh_private_key_file = optional(string)
    ssh_private_key      = optional(string)
    instance_token       = string
  })
  sensitive = true
}

variable "extra_hostvars" {
  description = "Optional additional hostvars merged into ansible_host variables."
  type        = map(any)
  default     = {}
}

