# AUTOGENERATED by tf-ansible-gen from backbone_network/meta/argument_specs.yml
# DO NOT EDIT. Run `make regen-modules` to regenerate.
#
# Contract sha256: c94467188cd8564d03936a6ac5e30e55260d471602102b456edc843fd2447700

variable "arguments" {
  description = <<-EOT
    Typed payload mirroring provision.options in argument_specs.yml.

    Fields declared `required: true` (no `default:`) in argument_specs are
    required at the Terraform layer too — `tofu plan` fails fast if the
    caller omits them. Fields with a `default:` are rendered as
    `optional(<type>, <default>)`. All other fields are
    `optional(<type>)` and arrive as null when omitted (the role must
    handle null explicitly).
  EOT
  type = object({
    backbone_dir = string
    backbone_subnet = string
    border_subnet = string
  })
}

variable "host_name" {
  description = "Inventory host that should receive this workload apply or cleanup."
  type        = string
}

variable "connection_data" {
  description = "Normalized transport/auth contract for the target Linux host."
  type = object({
    host                 = string
    user                 = string
    password             = optional(string)
    connection           = string
    network_os           = string
    ssh_private_key_file = optional(string)
    ssh_private_key      = optional(string)
    instance_token       = string
  })
  sensitive = true
}

variable "extra_hostvars" {
  description = "Optional additional hostvars merged into ansible_host variables."
  type        = map(any)
  default     = {}
}

