---
- name: restart firezone
  community.docker.docker_compose_v2:
    project_src: "{{ fz_firezone_dir }}"
    state: restarted
    wait: true
  become: true
  notify: apply firezone init policies

- name: apply firezone init policies
  community.docker.docker_container_exec:
    container: firezone-firezone-1
    command: "sh /var/firezone-init/firezone-init.sh"
  changed_when: false
  become: true
