#!/usr/bin/env bash
# AUTOGENERATED by tf-ansible-gen from
# tf-ansible-gen/tf_ansible_gen/templates/files/run_apply.sh.
# DO NOT EDIT. Run `make regen-modules` to regenerate; edits to this
# copy will be overwritten on the next regen and the drift-trap test
# in tf-ansible-gen will fail.
#
# run_apply.sh — Ansible runner for tf-ansible-gen-emitted wrappers.
#
# Required env vars:
#   contract_version   — sha256:<hex> of argument_specs.yml; verified on entry
#   role_dir           — absolute path to the role source (roles/<name>/)
#   workload_kind      — role name (used for assertions/logs)
#   workload_lifecycle — provision|destroy
#   workload_payload   — JSON object; published as top-level Ansible vars
#   inventory_host
#   ansible_user
#   ansible_network_os
#
# Optional env vars:
#   ansible_connection           — default: ssh
#   ansible_password
#   ansible_ssh_private_key_file
#   ansible_ssh_private_key_content (mutually exclusive with _file)
#   extra_hostvars               — JSON object
#   collection_root              — defaults to $(realpath "$role_dir/../..")
#   host_name                    — inventory entry name; defaults to inventory_host

set -euo pipefail

# ── SSH transport reliability defaults ─────────────────────────────────────
: "${ANSIBLE_SSH_RETRIES:=5}"
: "${ANSIBLE_TIMEOUT:=30}"
export ANSIBLE_SSH_RETRIES ANSIBLE_TIMEOUT

_existing_ssh_args="${ANSIBLE_SSH_ARGS:-}"
_extra_ssh_args=""
[[ "$_existing_ssh_args" != *"ConnectTimeout="*       ]] && _extra_ssh_args+=" -o ConnectTimeout=30"
[[ "$_existing_ssh_args" != *"ServerAliveInterval="*  ]] && _extra_ssh_args+=" -o ServerAliveInterval=15"
[[ "$_existing_ssh_args" != *"ServerAliveCountMax="*  ]] && _extra_ssh_args+=" -o ServerAliveCountMax=4"
if [[ -n "$_extra_ssh_args" ]]; then
  ANSIBLE_SSH_ARGS="${_existing_ssh_args}${_extra_ssh_args}"
fi
export ANSIBLE_SSH_ARGS
unset _existing_ssh_args _extra_ssh_args

# ── Contract drift check ───────────────────────────────────────────────────
spec_path="${role_dir}/meta/argument_specs.yml"
if [[ ! -f "$spec_path" ]]; then
  echo "ERROR: contract drift check: argument_specs.yml not found at $spec_path" >&2
  exit 2
fi
actual_hash="sha256:$(sha256sum "$spec_path" | awk '{print $1}')"
if [[ "$actual_hash" != "$contract_version" ]]; then
  cat >&2 <<EOF
ERROR: argument_specs.yml drift detected for workload '${workload_kind}'.
  Wrapper module baked: ${contract_version}
  Live file hash:       ${actual_hash}
  File:                 ${spec_path}
Fix: regenerate the wrapper modules with tf-ansible-gen.
EOF
  exit 2
fi

# ── Defaults & temp dir ────────────────────────────────────────────────────
ansible_connection="${ansible_connection:-ssh}"
ansible_password="${ansible_password:-}"
ansible_ssh_private_key_file="${ansible_ssh_private_key_file:-}"
ansible_ssh_private_key_content="${ansible_ssh_private_key_content:-}"
extra_hostvars="${extra_hostvars:-}"
host_name="${host_name:-${inventory_host}}"
collection_root="${collection_root:-$(realpath "${role_dir}/../..")}"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

# ── Materialize raw SSH key ────────────────────────────────────────────────
if [[ -n "$ansible_ssh_private_key_content" ]]; then
  if [[ -n "$ansible_ssh_private_key_file" ]]; then
    echo "ERROR: ansible_ssh_private_key_file and ansible_ssh_private_key_content are mutually exclusive" >&2
    exit 2
  fi
  (
    umask 077
    printf '%s' "$ansible_ssh_private_key_content" > "$tmp_dir/ssh.key"
  )
  ansible_ssh_private_key_file="$tmp_dir/ssh.key"
  unset ansible_ssh_private_key_content
fi

# ── Build inventory.ini ─────────────────────────────────────────────────────
host_line="${host_name} ansible_host=\"${inventory_host}\" ansible_user=\"${ansible_user}\" ansible_connection=\"${ansible_connection}\" ansible_network_os=\"${ansible_network_os}\""

if [[ -n "${ansible_ssh_private_key_file}" ]]; then
  host_line="${host_line} ansible_ssh_private_key_file=\"${ansible_ssh_private_key_file}\""
fi
if [[ -n "${ansible_password}" ]]; then
  host_line="${host_line} ansible_password=\"${ansible_password}\""
fi
if [[ -n "${extra_hostvars}" ]] && [[ "${extra_hostvars}" != "{}" ]]; then
  extra_kv="$(echo "${extra_hostvars}" | jq -r 'to_entries[] | "\(.key)=\"\(.value)\""' | tr '\n' ' ')"
  host_line="${host_line} ${extra_kv}"
fi

cat > "$tmp_dir/inventory.ini" <<INVENTORY
[all]
${host_line}
INVENTORY

# ── Materialize payload as a JSON file ─────────────────────────────────────
# Passing the payload through a file avoids the double-escaping rabbit hole
# that --extra-vars "key=value" introduces when the value contains
# backslash-escaped JSON strings (e.g. ".*\\.ru" regex literals): the shell
# layer + Jinja resolution layer eat one backslash each, which then breaks
# from_json.  Reading the file directly preserves byte-for-byte fidelity.
printf '%s' "${workload_payload}" > "$tmp_dir/workload_payload.json"

cat > "$tmp_dir/extra_vars.json" <<JSON
{
  "workload_kind": "${workload_kind}",
  "workload_lifecycle": "${workload_lifecycle}",
  "workload_payload_path": "$tmp_dir/workload_payload.json"
}
JSON

# ── Build wrapper playbook ──────────────────────────────────────────────────
cat > "$tmp_dir/play.yml" <<'PLAY'
- name: tf-ansible-gen wrapper
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Decode workload payload
      ansible.builtin.set_fact:
        workload_payload_vars: >-
          {{ lookup('ansible.builtin.file', workload_payload_path) | from_json }}

    - name: Publish payload as top-level vars
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
      loop: "{{ workload_payload_vars | dict2items }}"

    - name: Dispatch to role lifecycle entrypoint
      ansible.builtin.include_role:
        name: "{{ workload_kind }}"
        tasks_from: "{{ workload_lifecycle }}"
PLAY

cd "$collection_root"

ansible-playbook -i "$tmp_dir/inventory.ini" "$tmp_dir/play.yml" \
  --extra-vars "@$tmp_dir/extra_vars.json"
